DECLARE @CPF VARCHAR(50)
DECLARE @NOME VARCHAR(100)
DECLARE @DATA_NASCIMENTO DATE
DECLARE @IDADE INT
DECLARE @SAIDA VARCHAR(500)

SET @CPF='1471156710'

SELECT @NOME= NOME, @DATA_NASCIMENTO= DATA_NASCIMENTO, @IDADE = IDADE FROM CLIENTE WHERE CPF = @CPF

SET @SAIDA =  'O PRIMEIRO NOME DO CLIENTE É ' + @NOME + ' CUJO CPF É ' + @CPF + ', CORRESPONDE A '+ SUBSTRING(@NOME, 1, CHARINDEX(' ', @NOME)-1) 

PRINT @NOME
PRINT @DATA_NASCIMENTO
PRINT @IDADE

--SELECT * FROM CLIENTE

--1471156710
--19290992743
--23412632331

--CHARINDEX TRAZ O INDEX DE UMA DETERMINADA AÇÃO DENTRO DO TEXTO, COMO POR EXEMPLO UM ESPAÇO
--SUBSTRING TRAZ O INDEX DO TEXTO ATÉ UM DETERMINADO MOMENTO ESPECIFICADO.

--SELECT NOME, CHARINDEX(' ', NOME), SUBSTRING(NOME, 1, CHARINDEX(' ', NOME)-1) FROM CLIENTE -- TRAZ O PRIMEIRO NOME DO CLIENTE

PRINT @SAIDA
PRINT @DATA_NASCIMENTO
PRINT @IDADE