CREATE TABLE TAB_IDENTITY (
    ID INT IDENTITY(1,1) NOT NULL, 
    DESCRITOR VARCHAR (20) NULL
);


INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE X');

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE Y');

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE Z');

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE A');

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE W');

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE A');

select * from TAB_IDENTITY

DELETE FROM TAB_IDENTITY
WHERE ID=1

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE B');


DELETE FROM TAB_IDENTITY
WHERE ID=6

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE C');


CREATE TABLE TAB_IDENTITY_2 (
    ID INT IDENTITY(100,5) NOT NULL, 
    DESCRITOR VARCHAR (20) NULL
);

INSERT INTO TAB_IDENTITY_2 (DESCRITOR) 
VALUES ('CLIENTE W');

INSERT INTO TAB_IDENTITY_2 (DESCRITOR) 
VALUES ('CLIENTE A');

SELECT * FROM TAB_IDENTITY_2

INSERT INTO TAB_IDENTITY_2 (ID, DESCRITOR) 
VALUES (255,'CLIENTE W');
