BEGIN TRANSACTION 

SELECT * FROM VENDEDORES

UPDATE VENDEDORES
SET COMISSAO = COMISSAO * 1.10

COMMIT


BEGIN TRANSACTION 

INSERT INTO VENDEDORES 
VALUES ('239', 'Maria Joana', 'Copacabana', '0.2', '2015-01-01', 1);

SELECT * FROM VENDEDORES

ROLLBACK