
CREATE TABLE PRODUTOS (
    CODIGO VARCHAR(10) NOT NULL, 
    DESCRITOR VARCHAR(100) NULL, 
    SABOR VARCHAR(50) NULL, 
    TAMANHO VARCHAR(50) NULL, 
    EMBALAGEM VARCHAR(50) NULL, 
    PRECO_LISTA FLOAT NULL, 
    PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDORES (
    MATRICULA VARCHAR(5) NOT NULL, 
    NOME VARCHAR(100) NULL, 
    BAIRRO VARCHAR(50) NULL, 
    COMISSAO FLOAT NULL, 
    DATA_ADMISSAO DATE NULL, 
    FERIAS BIT NULL, 
    PRIMARY KEY (MATRICULA)
);

DROP TABLE CLIENTE(
	CPF VARCHAR(11) NOT NULL,
	NOME VARCHAR(100)NULL,
	ENDEREÇO VARCHAR(150) NULL,
	BAIRRO VARCHAR(50) NULL,
	CIDADE VARCHAR(50) NULL,
	ESTADO VARCHAR(50) NULL,
	CEP VARCHAR(8) NULL,
	DATA_NASCIMENTO DATE NULL,
	IDADE INT NULL,
	GENERO VARCHAR(1),
	LIMITE_CREDITO FLOAT NULL,
	VOLUME_COMPRA FLOAT,
	PRIMEIRA_COMPRA BIT NULL,
	PRIMARY KEY (CPF)
);

CREATE TABLE TABELA_DE_VENDAS (
    NUMERO VARCHAR(5) NOT NULL, 
    DATA_VENDA DATE NULL, 
    CPF VARCHAR(11) NOT NULL, 
    MATRICULA VARCHAR(11) NOT NULL, 
    IMPOSTO FLOAT NULL, 
    PRIMARY KEY (NUMERO)
);

ALTER TABLE TABELA_DE_VENDAS 
ADD CONSTRAINT FK_CLIENTE
FOREIGN KEY (CPF) REFERENCES CLIENTE (CPF);

ALTER TABLE TABELA_DE_VENDAS 
ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

ALTER TABLE TABELA_DE_VENDAS
ALTER COLUMN MATRICULA VARCHAR(5) NOT NULL;

ALTER TABLE TABELA_DE_VENDAS 
ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

CREATE TABLE ITENS_VENDIDOS (
    NUMERO VARCHAR(5) NOT NULL, 
	CODIGO VARCHAR(10) NOT NULL,
    QUANTIDADE INT NULL,
	PRECO FLOAT,
    PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE ITENS_VENDIDOS
ADD CONSTRAINT FK_TABELA_DE_VENDAS
FOREIGN KEY (NUMERO) REFERENCES TABELA_DE_VENDAS (NUMERO);


ALTER TABLE ITENS_VENDIDOS
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);

ALTER TABLE CLIENTE
ALTER COLUMN PRIMEIRA_COMBRA 