

MERGE INTO PRODUTOS A
USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO
WHEN MATCHED THEN
UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;


MERGE INTO CLIENTE A
USING VENDEDORES B
ON A.BAIRRO = B.BAIRRO
WHEN MATCHED THEN
UPDATE 
SET A.VOLUME_COMPRA =  A.VOLUME_COMPRA * 1.30;
