DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @ANO INT;
DECLARE @MES INT;
DECLARE @I INT;
DECLARE @TOTAL_VENDAS FLOAT;
DECLARE @TABELA_FINAL TABLE (CPF VARCHAR(11), NOME VARCHAR(100), MES INT, ANO INT, VALOR_TOTAL FLOAT);
SET @I = 1;
SET @ANO = 2015;
SET @MES = 1;
SELECT @NUMERO_CLIENTES = COUNT (*) FROM CLIENTE

WHILE @I < = @NUMERO_CLIENTES
BEGIN
SELECT @CPF = X.CPF, @NOME = X.NOME
	FROM(
	SELECT ROW_NUMBER () OVER (ORDER BY CPF) AS RowNum, * from CLIENTE
	)X
WHERE X.RowNum = @I

SELECT
@TOTAL_VENDAS = SUM(ITENS_VENDIDOS.QUANTIDADE * ITENS_VENDIDOS.PRECO) 
FROM Notas
join ITENS_VENDIDOS on NOTAS.NUMERO = ITENS_VENDIDOS.NUMERO 
where Notas.CPF = @CPF
AND YEAR(Notas.DATA) = @ANO AND MONTH(NOTAS.DATA) = @MES

INSERT INTO @TABELA_FINAL VALUES(@CPF, @NOME, @MES, @ANO, @TOTAL_VENDAS)
																												--RETIRANDO ESPAÇO EM BRANCO E COLOCANDO CASAS DECIMAIS
PRINT 'VENDAS PARA ' + @CPF + ' - ' + @NOME + ' NO MÊS ' + CONVERT(VARCHAR(2),@MES) + ' E ANO ' + CONVERT(VARCHAR(4),@ANO) + ' FOI DE ' + TRIM(STR(@TOTAL_VENDAS,15,2));
SET @I = @I +1 

END;

SELECT * FROM @TABELA_FINAL





