CREATE TRIGGER TG_ITENS_VENDIDOS
ON ITENS_VENDIDOS
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
DELETE FROM FATURAMENTO

INSERT INTO FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TABELA_DE_VENDAS TV 
INNER JOIN ITENS_VENDIDOS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

SELECT * FROM FATURAMENTO


END


SELECT * FROM FATURAMENTO

INSERT INTO TABELA_DE_VENDAS 
VALUES (
    '0108', '2018-05-16', '1471156710', '235', 0.18
);

INSERT INTO ITENS_VENDIDOS 
VALUES (
    '0108', '1000889', 150, 10
);

UPDATE ITENS_VENDIDOS
SET QUANTIDADE =200 WHERE NUMERO ='0108'

DELETE FROM ITENS_VENDIDOS
WHERE NUMERO ='0108'