SELECT * FROM PRODUTOS ORDER BY CODIGO;

SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS 
ORDER BY CODIGO_DO_PRODUTO;

UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS 
SET PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20

SELECT 
A.CODIGO AS CODIGO_MINHA_TABELA,
A.PRECO_LISTA AS PRECO_MINHA_TABELA,
B.CODIGO_DO_PRODUTO AS CODIGO_TABELA_APOIO,
B.PRECO_DE_LISTA AS PRECO_TABELA_APOIO
FROM PRODUTOS A
JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO


UPDATE A
SET A.PRECO_LISTA = B.PRECO_DE_LISTA
FROM PRODUTOS A
JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO


UPDATE A
SET A.VOLUME_COMPRA =  A.VOLUME_COMPRA * 1.30
FROM CLIENTE A
INNER JOIN VENDEDORES B
ON A.BAIRRO = B.BAIRRO

