IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL DROP TABLE TABELA_TESTE
IF OBJECT_ID('TABELA_TESTE', 'U') IS NULL CREATE TABLE TABELA_TESTE (ID VARCHAR(10))
--------------------------------------------------------------------------------------------------
DECLARE @IDADE_ALUNO INT;
DECLARE @FORMADO_INGLES BIT;
DECLARE @FORMADO_ALEMAO BIT;

SET @IDADE_ALUNO = 17;
SET @FORMADO_INGLES = 1;
SET @FORMADO_ALEMAO = 0;

IF ((@IDADE_ALUNO >= 18 OR @FORMADO_INGLES = 1) OR (@IDADE_ALUNO < 18 AND @FORMADO_ALEMAO = 1))
  PRINT 'EXPRESSAO VERDADEIRA';
ELSE
  PRINT 'EXPRESSAO FALSA';
-------------------------------------------------------------------------------------------------

SELECT GETDATE()

SELECT DATENAME(WEEKDAY,GETDATE())

SELECT GETDATE(), DATEADD(DAY, 5, GETDATE())

SELECT DATENAME(WEEKDAY, DATEADD(DAY, 5, GETDATE()))

---------------------------------------------------------
DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT

SET @NUMERO_DIAS= 12;
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()))
PRINT @DIA_sEMANA

IF @DIA_SEMANA= 'DOMINGO' OR @DIA_SEMANA = 'SÁBADO'
	PRINT 'ESTE DIA É FIM DE SEMANA'
ELSE
	PRINT 'ESTE DIA É DIA DE SEMANA'
----------------------------------------------------------
SELECT * FROM CLIENTE


DECLARE @LIMITE_MAXIMO FLOAT
DECLARE @LIMITE_ATUAL FLOAT
DECLARE @BAIRRO VARCHAR(20)

SET @LIMITE_MAXIMO = 50000
SET @BAIRRO = 'Jardins'
SELECT @LIMITE_ATUAL= SUM(LIMITE_CREDITO) FROM CLIENTE WHERE BAIRRO=@BAIRRO

IF @LIMITE_MAXIMO <= @LIMITE_ATUAL
PRINT 'VALOR MÁXIMO ATINGIDO'
ELSE 
PRINT 'VALOR OK'
-------------------------------------------------------------------------

DECLARE @LIMITE_MAXIMO FLOAT
--DECLARE @LIMITE_ATUAL FLOAT
DECLARE @BAIRRO VARCHAR(20)

SET @LIMITE_MAXIMO = 50000
SET @BAIRRO = 'Jardins'

IF @LIMITE_MAXIMO <= (SELECT SUM(LIMITE_CREDITO) FROM CLIENTE WHERE BAIRRO=@BAIRRO)
PRINT 'VALOR MÁXIMO ATINGIDO'
ELSE 
PRINT 'VALOR OK'


