CREATE TABLE PADRAO
(ID INT IDENTITY (1,1) NOT NULL,
DESCRITOR VARCHAR(20) NULL,
ENDERECO VARCHAR(20)NULL,
CIDADE VARCHAR (20) DEFAULT 'Rio de Janeiro',
DATA_CRIACAO DATE DEFAULT GETDATE())
;

INSERT INTO PADRAO
(DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO)
VALUES('X', 'RUA PROJETADA A', 'SÃO PAULO', '2018-03-30');

SELECT * FROM PADRAO


INSERT INTO PADRAO
(DESCRITOR)
VALUES('Y')