DECLARE @LIMITE_MINIMO INT
DECLARE @LIMITE_MAXIMO INT

SET @LIMITE_MINIMO = 3
SET @LIMITE_MAXIMO = 15


PRINT 'ENTREI NO LOOPING'
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
	PRINT @LIMITE_MINIMO
	SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1
END
PRINT 'SAI DO LOOPING'
